notif:
  death:
    enabled: true
    timer:
      enabled: true
  bot:
    token: dummytoken
    chat: dummychat
  silent:
    enabled: true
  delay: 15
  message:
    death: â˜ ï¸ `%msg%`
    join: ğŸ’â›ï¸ `%msg% vient de se connecter.`
    quit: ğŸŒ’ `%msg% s'est dÃ©connectÃ©.`
    success: ğŸ† `%msg% a obtenu un succÃ¨s %success%! GG!`
    shutdown: â™»ï¸ğŸ”‹ `extinction du serveur.`
    rage:
    - ğŸ–¥ï¸ğŸ‘‰ğŸªŸ `Je crois que %msg% vient de jeter son PC par la fenÃªtre, j'ai perdu la connexion.`
    - ğŸ¼ğŸ‘¶ `%msg% a encore ragequit... quelquâ€™un lui passe une tÃ©tine ?`
    - ğŸ§‚ğŸ˜¤ `%msg% a des larmes plus salÃ©es que lâ€™ocÃ©an Atlantique.`
    - ğŸª¦ğŸ’€ `%msg% est mortâ€¦ encore. Mais cette fois il a ragequit avant le respawn.`
    - ğŸ»ğŸ˜¢ `%msg% mÃ©rite un petit violon pour son dÃ©part dramatique.`
    - ğŸšªğŸƒ `%msg% a tentÃ© de fuir ! Mais visiblement mÃªme Ã§a c'est chaud...`
    - ğŸ§¹ğŸ—‘ï¸ `%msg% a ragequit... On espÃ¨re tous qu'il va pas glisser sur ses larmes et mourir une deuxiÃ¨me fois.`
    - ğŸ›‘ğŸ¤¡ `%msg% pensait Ãªtre un pro, mais la dÃ©connexion Ã©tait plus rapide que son skill.`
    - ğŸ”ğŸ³ï¸ `%msg% a quittÃ© comme une poule devant un renard.`
    - ğŸ¥²ğŸ’” `%msg% a ragequit Ã  %location%... si quelquâ€™un peut venir lâ€™aider, il me fait presque de la peine.`
    - ğŸ†ğŸ¥ˆğŸ˜‚ `%msg% nâ€™a pas perduâ€¦ il a juste ragequit en â€œgrand championâ€ de la deuxiÃ¨me place.`
    - ğŸ“‰ğŸ“‰ğŸ˜‚ `%msg% fait encore chuter la courbe de motivation de lâ€™Ã©quipe.`
    - ğŸ§ŸğŸ§  `%msg% a utilisÃ© 0% de son cerveau avant de ragequit.`
    - ğŸ¯ğŸ–±ï¸â„ï¸ `%msg% a visiblement enfin rÃ©ussi a toucher son frigo avec sa souris.`
    - ğŸ¦¥ğŸ’¤ `%msg% a ragequit plus vite quâ€™il ne joue. Impressionnant.`
    - ğŸ¤¹â€â™‚ï¸ğŸ™„ `%msg% jongle entre mourir et ragequit.`
    - ğŸ”®ğŸ¤” `%msg% n'a pas ragequit. Il â€œprÃ©voitâ€ juste de revenir perdre plus tard.`
    - ğŸ¿ğŸ˜‚ğŸ¬ `%msg% offre toujours un bon spectacle de ragequit, merci pour le divertissement.`
    - ğŸ¥²ğŸšª `%msg% a confondu la touche â€œQuitterâ€ avec â€œGagnerâ€ (Spoiler, elle existe pas la touche lool).`
    - ğŸ®ğŸ•¹ï¸ğŸ‘¾ `%msg% croit que couper le jeu est une compÃ©tence eSport.`
    - ğŸš«ğŸ… `%msg% gagne la mÃ©daille dâ€™or du ragequit le plus pathÃ©tique.`
    - ğŸºğŸ¹ğŸ· `%msg%, et si t'allais boire un coup pour oublier ce qui vient de se passer ? Promis je dis rien aux autres.`
    deathTime: â±ï¸ `a vÃ©cu %msg%`
  join:
    enabled: true
  quit:
    enabled: true
  success:
    enabled: true
    categories:
    - adventure
    - husbandry
    - story
    - nether
    - end
  free:
    enabled: true
  rage:
    enabled: true
    delay: 30
  shutdown:
    enabled: true
