notif:
  death:
    enabled: true
  bot:
    token: tokendummy
    chat: chatdummy
  delay: 15
  silent:
    enabled: true
  message:
    death: â˜ ï¸ `%msg%`
    join: ğŸ’â›ï¸ `%msg% vient de se connecter.`
    quit: ğŸŒ’ `%msg% s'est dÃ©connectÃ©.`
    success: ğŸ¯ `%msg% a obtenu un succÃ¨s %success%! GG!`
    shutdown: â™»ï¸ğŸ”‹ `extinction du serveur.`
  join:
    enabled: true
  quit:
    enabled: true
  shutdown:
    enabled: true
  success:
    enabled: true
    categories: 
      - adventure
      - husbandry
      - story
      - nether
      - end
